export const SKILLS = [
  "HTML",
  "CSS",
  "SASS",
  "Bootstrap",
  "JavaScript",
  "React",
  "Next.js",
  "TypeScript",
  "Node.js",
  "MongoDB",
  "PostgreSQL",
  "GraphQL",
  "Tailwind CSS",
  "Sass",
  "Figma",
  "Adobe XD",
  "Git",
  "Docker",
  "AWS",
  "CI/CD",
  "Agile",
  "Scrum",
  "Kanban",
  "Jira",
  "Confluence",
  "Slack",
  "Zoom",
  "Microsoft Teams",
  "Trello",
  "Asana",
  "Notion",
  "Monday.com",
  "Basecamp",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Heroku",
  "Netlify",
  "Vercel",
  "Firebase",
  "Azure",
  "GCP",
  "DigitalOcean",
  "Linode",
];
export const EXPERIENCES = [
  {
    jobTitle: "Academic Tutor",
    jobDescription:
      "Tutoring in web development and abstract data types, also marking assignments for students.",
    jobDate: "Feb 2022 - Present",
    company: "University of Tasmania",
    position: "left",
  },
  {
    jobTitle: "Academic Tutor",
    jobDescription:
      "Tutoring in web development and abstract data types, also marking assignments for students.",
    jobDate: "Feb 2022 - Present",
    company: "University of Tasmania",
    position: "right",
  },
  // other experiences...
];