export const SKILLS = [
  "HTML",
  "CSS",
  "SASS",
  "Bootstrap",
  "JavaScript",
  "React",
  "Next.js",
  "Vite",
  "TypeScript",
  "Node.js",
  "MongoDB",
  "PostgreSQL",
  "GraphQL",
  "Tailwind CSS",
  "Sass",
  "Figma",
  "Adobe XD",
  "Git",
  "Docker",
  "AWS",
  "CI/CD",
  "Agile",
  "Scrum",
  "Kanban",
  "Jira",
  "Confluence",
  "Slack",
  "Zoom",
  "Microsoft Teams",
  "Trello",
  "Asana",
  "Notion",
  "Monday.com",
  "Basecamp",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Heroku",
  "Netlify",
  "Vercel",
  "Firebase",
  "Azure",
  "GCP",
  "DigitalOcean",
  "Linode",
];
export const EXPERIENCES = [
  {
    jobTitle: "Academic Tutor",
    jobDescription:
      "Tutoring in web development and abstract data types, also marking assignments for students.",
    jobDate: "Feb 2022 - Present",
    company: "University of Tasmania",
    position: "left",
  },
  {
    jobTitle: "Academic Tutor",
    jobDescription:
      "Tutoring in web development and abstract data types, also marking assignments for students.",
    jobDate: "Feb 2022 - Present",
    company: "University of Tasmania",
    position: "right",
  },
  // other experiences...
];
export const ITEMS = [
  {
    id: 1,
    color: "from-red-300 to-blue-300",
    title: "React Commerce",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.",
    img: "https://images.pexels.com/photos/18073372/pexels-photo-18073372/free-photo-of-young-man-sitting-in-a-car-on-a-night-street.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    link: "https://auroraweb.com.au",
  },
  {
    id: 2,
    color: "from-blue-300 to-violet-300",
    title: "Next.js Medium Blog",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.",
    img: "https://images.pexels.com/photos/18023772/pexels-photo-18023772/free-photo-of-close-up-of-a-person-holding-a-wristwatch.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    link: "https://auroraweb.com.au",
  },
  {
    id: 3,
    color: "from-violet-300 to-purple-300",
    title: "Vanilla Book App",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.",
    img: "https://images.pexels.com/photos/6894528/pexels-photo-6894528.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    link: "https://auroraweb.com.au",
  },
  {
    id: 4,
    color: "from-purple-300 to-red-300",
    title: "Spotify Music App",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.",
    img: "https://images.pexels.com/photos/18540208/pexels-photo-18540208/free-photo-of-wood-landscape-water-hill.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    link: "https://auroraweb.com.au",
  },
];
