export const SKILLS = [
  "HTML",
  "CSS",
  "SASS",
  "Bootstrap",
  "JavaScript",
  "React",
  "Next.js",
  "Vite",
  "TypeScript",
  "Node.js",
  "MongoDB",
  "PostgreSQL",
  "GraphQL",
  "Tailwind CSS",
  "Sass",
  "Figma",
  "Adobe XD",
  "Git",
  "Docker",
  "AWS",
  "CI/CD",
  "Agile",
  "Scrum",
  "Kanban",
  "Jira",
  "Confluence",
  "Slack",
  "Zoom",
  "Microsoft Teams",
  "Trello",
  "Asana",
  "Notion",
  "Monday.com",
  "Basecamp",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Heroku",
  "Netlify",
  "Vercel",
  "Firebase",
  "Azure",
  "GCP",
  "DigitalOcean",
  "Linode",
];
export const EXPERIENCES = [
  {
    jobTitle: "Full-Stack Developer",
    jobDescription:
      "Developing web applications and APIs, also designing user interfaces and experiences.",
    jobDate: "Jan 2023 - Present",
    company: "Aurora Web",
    position: "left",
  },
  {
    jobTitle: "Frontend Developer",
    jobDescription:
      'Prototyping and developing the mobile application "WaterCan Profit" with Figma and Flutter.',
    jobDate: "Jul 2022 - Present",
    company: "University of Tasmania",
    position: "right",
  },
  {
    jobTitle: "Academic Tutor",
    jobDescription:
      "Tutoring in web development and abstract data types, also marking assignments for students.",
    jobDate: "Feb 2022 - Present",
    company: "University of Tasmania",
    position: "left",
  },
  {
    jobTitle: "Full-Stack Developer",
    jobDescription:
      "Developed an e-commerce platform for selling online courses and educational products, featuring integrated video streaming for online learning.",
    jobDate: "Jul 2018 - Feb 2020",
    company: "Beijing Young Naturalist Education Technology Co.",
    position: "right",
  },
  {
    jobTitle: "Project Manager",
    jobDescription:
      "Restructuring the company’s business processes into an ERP system and training staff to use the system to improve the overall efficiency of the business.",
    jobDate: "Aug 2016 - May 2018",
    company: "Hangzhou Ciyuanxing Trading Co.",
    position: "left",
  },
  {
    jobTitle: "Project Manager",
    jobDescription:
      "Led the Hangzhou branch in customizing and selling ERP systems to SMEs, achieving a net profit margin of over 50% in two years.",
    jobDate: "Aug 2014 - Aug 2016",
    company: "Beijing Zhongweikang Pharmaceutical Investment Co.",
    position: "right",
  },
  {
    jobTitle: "Automation Engineer",
    jobDescription:
      "Restructuring the company’s business processes into an ERP system and training staff to use the system to improve the overall efficiency of the business.",
    jobDate: "Aug 2013 - Aug 2014",
    company: "Nanjing CEC-PANDA LCD Technology Co.",
    position: "left",
  },
  {
    jobTitle: "Information Technology Specialist",
    jobDescription:
      "Produced product manuals and database with Photoshop and Il- lustrator, and modified the ERP system to improve the information approval process.",
    jobDate: "Feb 2013 - Aug 2013",
    company: "Beijing Tiandeqin Automobile Parts Co.",
    position: "right",
  },
  {
    jobTitle: "Implementation Engineer",
    jobDescription:
      "Participated in the implementation of a wastewater treatment plant project, commissioned and maintained the IT infrastructure within the company.",
    jobDate: "Aug 2011 - Feb 2013",
    company: "Beijing Fubang Zhida Automation Technology Co.",
    position: "left",
  },
  {
    jobTitle: "Full-Stack Developer",
    jobDescription:
      "Managed full-stack development of the university’s BBS website, focusing on user engagement and site security.",
    jobDate: "Oct 2009 - Jun 2011",
    company: "Southeast University",
    position: "right",
  },
];
export const ITEMS = [
  {
    id: 1,
    color: "from-red-300 to-blue-300",
    title: "React Commerce",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.",
    img: "https://images.pexels.com/photos/18073372/pexels-photo-18073372/free-photo-of-young-man-sitting-in-a-car-on-a-night-street.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    link: "https://auroraweb.com.au",
  },
  {
    id: 2,
    color: "from-blue-300 to-violet-300",
    title: "Next.js Medium Blog",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.",
    img: "https://images.pexels.com/photos/18023772/pexels-photo-18023772/free-photo-of-close-up-of-a-person-holding-a-wristwatch.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    link: "https://auroraweb.com.au",
  },
  {
    id: 3,
    color: "from-violet-300 to-purple-300",
    title: "Vanilla Book App",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.",
    img: "https://images.pexels.com/photos/6894528/pexels-photo-6894528.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    link: "https://auroraweb.com.au",
  },
  {
    id: 4,
    color: "from-purple-300 to-red-300",
    title: "Spotify Music App",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores ab id ad nesciunt quo aut corporis modi? Voluptate, quos sunt dolorum facilis, id eum sequi placeat accusantium saepe eos laborum.",
    img: "https://images.pexels.com/photos/18540208/pexels-photo-18540208/free-photo-of-wood-landscape-water-hill.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    link: "https://auroraweb.com.au",
  },
];
